name: "TrunkVer"
description: "Get TrunkVer"
branding:
  icon: "chevron-up"
  color: "black"
inputs:
  with_v_suffix:
    description: "Whether to add the v suffix"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
  - uses: actions-rust-lang/setup-rust-toolchain@v1
  - uses: cargo-bins/cargo-binstall@main
  - name: Get TrunkVer
    shell: bash
    run: cargo binstall trunkver@0.1.1
  - name: Get TrunkVer Version (with v)
    shell: bash
    run: |
      trunkver --build-ref ${{ github.run_id }}-${{ github.run_number }} --source-ref ${{ github.sha }} --with-v
  - name: Get TrunkVer Version (without v)
    shell: bash
    run: |
      trunkver --build-ref ${{ github.run_id }}-${{ github.run_number }} --source-ref ${{ github.sha }}
outputs:
  version:
    description: "The version of TrunkVer"
  version_with_v:
    description: "The version of TrunkVer with v"
