---
name: "TrunkVer"
description: "Get TrunkVer"
inputs:
    with_v_suffix:
        description: "Whether to add the v suffix"
        required: false
        default: "false"
runs:
    using: "composite"
    steps:
        - name: Setup Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1

        - uses: cargo-bins/cargo-binstall@main

        - name: Get TrunkVer
          shell: bash
          run: cargo binstall --force --path trunkver

        - name: Get TrunkVer Version (with v)
          if: ${{ inputs.with_v_suffix == 'true' }}
          shell: bash
          run: trunkver --build-ref ${{ github.sha }} --source-ref ${{ github.ref }} --with_v
          id: trunkver_version_with_v

        - name: Get TrunkVer Version (without v)
          if: ${{ inputs.with_v_suffix != 'true' }}
          shell: bash
          run: trunkver --build-ref ${{ github.sha }} --source-ref ${{ github.ref }}
          id: trunkver_version_without_v

outputs:
    version:
        description: "The version of TrunkVer"
        value: ${{ steps.trunkver_version_with_v.outputs.stdout || steps.trunkver_version_without_v.outputs.stdout }}
