name: "TrunkVer"
description: "Get TrunkVer"
branding:
  icon: "chevron-up"
  color: "black"
outputs:
  version: ${{ steps.get_version.outputs.version }}
  version_with_v: ${{ steps.get_version.outputs.version_with_v }}
runs:
  using: "composite"
  steps:
  - uses: actions-rust-lang/setup-rust-toolchain@v1
  - uses: cargo-bins/cargo-binstall@main
  - name: Get TrunkVer
    shell: bash
    run: cargo binstall trunkver@0.1.1
  - name: Get TrunkVer Version (with v)
    shell: bash
    run: |
      echo "version_with_v=$(trunkver --build-ref ${{ github.run_id }}-${{ github.run_number }} --source-ref ${{ github.sha }} --with-v)" >> $GITHUB_OUTPUT
  - name: Get TrunkVer Version (without v)
    shell: bash
    run: |
      echo "version=$(trunkver --build-ref ${{ github.run_id }}-${{ github.run_number }} --source-ref ${{ github.sha }})" >> $GITHUB_OUTPUT
