name: "TrunkVer"
description: "Get TrunkVer"
branding:
  icon: "chevron-up"
  color: "black"
outputs:
  version:
    description: "The version of TrunkVer"
  version_with_v:
    description: "The version of TrunkVer with v"
runs:
  using: "composite"
  steps:
  - uses: actions-rust-lang/setup-rust-toolchain@v1
  - uses: cargo-bins/cargo-binstall@main
  - name: Get TrunkVer
    shell: bash
    run: cargo binstall trunkver@0.1.1
  - name: Get TrunkVer Version (with v)
    shell: bash
    run: |
      VERSION=$(trunkver --build-ref ${{ github.run_id }}-${{ github.run_number }} --source-ref ${{ github.sha }} --with-v)
      echo "version_with_v=$VERSION_WITH_V" >> $GITHUB_OUTPUT
  - name: Get TrunkVer Version (without v)
    shell: bash
    run: |
      VERSION=$(trunkver --build-ref ${{ github.run_id }}-${{ github.run_number }} --source-ref ${{ github.sha }})
      echo "version=$VERSION" >> $GITHUB_OUTPUT
